// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-opposite/DirectCommerce.tsx": () => import("../components/mockups/homepage-opposite/DirectCommerce.tsx"),
  "./components/mockups/homepage-opposite/SensoryImmersive.tsx": () => import("../components/mockups/homepage-opposite/SensoryImmersive.tsx")
};
